DROP TABLE IF EXISTS Operation;
DROP TABLE IF EXISTS Percapital_User;
DROP TABLE IF EXISTS Operation_Type;
DROP TABLE IF EXISTS Price_RV;
DROP TABLE IF EXISTS Stock_Exchange_Title;
DROP TABLE IF EXISTS Exchange_Rate;
DROP TABLE IF EXISTS Constant_Value;
DROP TABLE IF EXISTS Constant_Type;
DROP TABLE IF EXISTS Percapital_Role;

DROP FUNCTION login(VARCHAR, VARCHAR);
DROP FUNCTION get_users(INTEGER);
DROP FUNCTION get_roles(INTEGER);
DROP FUNCTION get_constant_types(INTEGER);
DROP FUNCTION get_constant_values(INTEGER);
DROP FUNCTION get_last_value_constant(INTEGER);
DROP FUNCTION get_computed_value(NUMERIC, NUMERIC);
DROP FUNCTION get_operations_stock_ammount_by_title(INTEGER,INTEGER);
DROP FUNCTION get_latest_exchange_rate();
DROP FUNCTION get_sell_operations(INTEGER);
DROP FUNCTION get_buy_operations(INTEGER);
