DROP INDEX IF EXISTS fkIdx_43;
DROP INDEX IF EXISTS fkIdx_50;
DROP INDEX IF EXISTS fkIdx_46;
DROP INDEX IF EXISTS fkIdx_54;

DROP TABLE IF EXISTS Operation;
DROP TABLE IF EXISTS Price_RV;
DROP TABLE IF EXISTS Stock_Exchange_Title;
DROP TABLE IF EXISTS Exchange_Rate;
DROP TABLE IF EXISTS Type_Value;
DROP TABLE IF EXISTS Constant_Type;
